[package]
name = "wordle"
version = "0.2.0"
description = "Minimalist command-line wordle game"

authors = ["Jack Willis <jack@attac.us>"]
license = "MIT"

edition = "2021"

[dependencies]
rand = "0.8"
