on: [push, pull_request]

name: Code coverage

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Run tarpaulin
      run: cargo tarpaulin --out Xml
    - name: Push to codecov.io
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
