on:  
  push:
    tags:
      - '*'

name: Github release

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p wordle-gui
      - run: cp target\release\wordle-gui.exe Wordle.exe
      - name: Edit executable resources
        run: >
          .\wordle-gui\vendor\rcedit-1.1.1\rcedit-x64.exe Wordle.exe
            --set-icon wordle-gui\images\icon.ico
            --set-file-version "{{ github.ref_name }}"
            --set-product-version "{{ github.ref_name }}" ;
      - name: Zip the package
        run: >
          Compress-Archive
            -LiteralPath LICENSE.html , Wordle.exe
            -DestinationPath "Wordle-${{ github.ref_name }}-windows.zip"
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: Wordle-${{ github.ref_name }}.zip
