on:  
  push:
    tags:
      - '*'

name: Github release

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-pc-windows-gnu
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release -p wordle-gui --target x86_64-pc-windows-gnu
      - name: Sign Windows binary
        run:
          echo "${{ secrets.WINDOWS_CERT }}" > www_attac_us.crt;
          echo "${{ secrets.WINDOWS_KEY }}" > www_attac_us.key;
          sudo apt install osslsigncode;
          osslsigncode sign -certs www_attac_us.crt -key www_attac_us.key
            -n "Wordle" -i https://www.attac.us/ 
            -t http://timestamp.digicert.com
            -in target/x86_64-pc-windows-gnu/release/wordle-gui.exe
            -out Wordle.exe;
      - name: Zip the package
        run: >
          export DIST=Wordle-${{ github.ref_name }};
          mkdir $DIST/;
          cp Wordle.exe $DIST/;
          cp LICENSE.html $DIST/;
          sudo apt install zip;
          zip -r $DIST.zip $DIST/;
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: Wordle-${{ github.ref_name }}.zip
