on:  
  push:
    tags:
      - '*'

name: Github release

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-pc-windows-gnu
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release -p wordle-gui --target x86_64-pc-windows-gnu
      - name: Sign Windows binary
        uses: jonfriesen/windows-signer-action@v1.0.0
        env:
          NAME: Jack Willis
          DOMAIN: https://www.attac.us
          BINARY: target/x86_64-pc-windows-gnu/release/wordle-gui.exe
          WINDOWS_CERT: ${{ secrets.WINDOWS_CERT }}
          WINDOWS_KEY: ${{ secrets.WINDOWS_KEY }}
      - name: Zip the package
        run: >
          export DIST=Wordle-${{ github.ref_name }}
          mkdir $DIST/
          cp target/x86_64-pc-windows-gnu/release/wordle-gui.exe $DIST/Wordle.exe
          cp LICENSE.html $DIST/
          sudo apt install zip
          zip -r $DIST.zip $DIST
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: Wordle-${{ github.ref_name }}.zip
