on: [push, pull_request]

name: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-pc-windows-gnu
      - name: Build for Linux
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      - name: Build for Windows
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-pc-windows-gnu
      - name: Rename binaries
        run: >
          mv target/x86_64-unknown-linux-gnu/release/wordle wordle-linux-x86_64;
          mv target/x86_64-unknown-linux-gnu/release/wordle-gui wordle-gui-linux-x86_64;
          mv target/x86_64-pc-windows-gnu/release/wordle.exe wordle.exe;
          mv target/x86_64-pc-windows-gnu/release/wordle-gui.exe wordle-gui.exe;
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LICENSE
            wordle-x86_64-linux
            wordle-gui-x86_64-linux
            wordle.exe
            wordle-gui.exe
