on: [push, pull_request]

name: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build for target x86_64-unknown-linux-gnu
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
          env: 
            RUSTFLAGS: -C target-feature=+crt-static # <https://msfjarvis.dev/posts/building-static-rust-binaries-for-linux/>
      - name: Rename binaries
        run: >
          mv target/x86_64-unknown-linux-gnu/release/wordle wordle-x86_64-linux;
          mv target/x86_64-unknown-linux-gnu/release/wordle-gui wordle-gui-x86_64-linux;
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LICENSE
            wordle-x86_64-linux
            wordle-gui-x86_64-linux
