on:  
  push:
    tags:
      - '*'

name: Github release

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p wordle-gui
      - name: Sign the binary
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          folder: 'target/release'
          recursive: false
      - name: Rename the binary
        run: mv target/release/wordle-gui.exe wordle.exe
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            wordle.exe
